### ISSUE TITLE
Genesis repipe doesn't contain stemcells job by default

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#117]
With v1.7.2

looks like the `stemcells` job was added to `.ci.yml`:
```
alpha: acf-global/alpha
groups:
- jobs:
  - stemcells
  name: '*'
- jobs:
  - stemcells
  name: upkeep
jobs:
- name: stemcells
  plan:
  - aggregate:
    - get: git
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: git
      outputs:
      - name: out
      params:
        REPO_OUT: out/git
        STEMCELLS: stemcells
      platform: linux
      run:
        args:
        - ci
        - stemcells
        path: git/bin/genesis
    task: update
  - params:
      rebase: true
      repository: out/git
    put: git
  public: true
  serial: true
sites:
  acf-global:
    auto:
      acf-devtest: true
      acf-eu01: true
      acf-preprod: true
      acf-prod: true
      alpha: true
    beta: acf-devtest
  acf-global-vcloud:
    auto:
      acf-tai-nam: true
      acf-tai-nl: true
    beta: acf-tai-nam
  aws-clients:
    acf-eu01:
      parent: acf-preprod
    auto:
      acf-devtest: true
    beta: acf-devtest
  vcloud-clients:
    acf-tai-nl:
      parent: acf-tai-nam
    auto:
      acf-tai-nam: true
    beta: acf-tai-nam

```
