### ISSUE TITLE
Add 'none' as an internal no-op kit

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#187]
In order to support the "training wheels we can take off" use case of Genesis, we should allow genesis repos to deploy full manifests without needing a kit.  To this end, rather than have a none-genesis-kit that has to be downloaded, we can bake 'none' in as a special path in the code to return mergable yaml files of nothing, and the various other places that the actual .genesis/kits/kit-version.tar.gz file gets used.

The caveat to supporting this is that the standard manifest will have to have two additional top-level keys of kit and params with the expected contents:
```
kit:
  name: none
  version: 0

params:
  env: <env name>
  bosh: <optional: bosh name>
  vault: <vault path>
```
