### ISSUE TITLE
Add meta.environment to <env>/name.yml

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#85]
There are some paths in vault that we would like to specify in `site/properties.yml` that differ only by the 'environment' section of the path.

eg: `(( vault "secret/aws/" meta.environment "shield/something:secret" ))`

Could the environment name be added to the `name.yml` file by default on environment creation? I think this could be generally useful.

**Comment by geofffranks** [comment]
Is meta.vault_prefix sufficient? It's defined in name.yaml

**Comment by bodymindarts** [comment]
`meta.vault_prefix` contains `"secret/<site>/<env>/<deployment"` but this is for referencing _another_ deployment in the same environment. Eg we are in `bosh-deployments` and want to get the `provisioning_key` from the shield deployment of the same environment.

**Comment by jhunt** [comment]
I have also run into this.

Having something like this would be awesome:

```
meta:
  deployment:
    type: redis
    site: aws
    env: sandbox
  vault_prefix: (( concat "secret/" meta.deployment.site "/" meta.deployment.env "/" meta.deployment.type" ))
```

Because then I can add something like this to global:

```
meta:
  cf:
    deployment_name: cf
  cf_vault_prefix: (( concat "secret/"  meta.deployment.site "/" meta.deployment.env "/" meta.cf.deployment_name ))

  creds:
    cf:
      admin: (( vault cf_vault_prefix "/admin:password" ))
```
