### ISSUE TITLE
VAULT_PREFIX does not work well when one deployment need to use secrets from another deployment

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#99]
In Concourse deployment, we need to specify the shield daemon public key, I could not use VAULT_PREFIX to get the vault path for the key directly, so I just hard coded the path to the shield pub key. It is not a problem, but it will be nice that if we could keep things more consistent.

I have thought of two solutions 1) set `VAULT_PREFIX=secret/${site}/$name` instead of `VAULT_PREFIX=secret/${site}/$name{DEPLOYMENT_NAME}`; 2) Bring in another variable, lets call it  `VAULT_ENV_PREFIX=secret/${site}/$name`. However, both of them have some disadvantages. The first one means we need to modify some path configure;   in the second case,   `VAULT_ENV_PREFIX` may not be used in some deployments.

Any thoughts?

**Comment by jhunt** [comment]
We normally do something like this:

```
# env/properties.yml
meta:
  env: your-env
  site: your-site
```

then, you can do this:

```
properties:
  shield:
    agent:
      public_key: (( concat "secret/" meta.site "/" meta.env "/rest/of/path:secret" ))
```
